### ISSUE TITLE
Read Me

### ISSUE THREAD

**Issue by OutlawDisco** [OutlawDisco/Hot-Takes#41]
A complete ReadMe file:

- Table of contents (done)
- Layout (done)
- User story
- Description
- Installation
- Questions
- License(done)
- Wireframe (update)
- Links(done)

**Comment by ctowns5** [comment]
Used Bens user story from G drive, Adrian's description from homepage, Angela's wireframes, edited the questions, updated the table of contents and added a place holder for a screenshot.
